IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('SISBTNUMER') AND type in ('U'))
    DROP TABLE SISBTNUMER

CREATE TABLE SISBTNUMER(
	SISBDSNUME varchar(50) PRIMARY KEY,
	SISBNONUME int NOT NULL,
)

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID('VERSAO_BANCO') AND type in ('U'))
    DROP TABLE VERSAO_BANCO

CREATE TABLE VERSAO_BANCO (
	ID_VERSAO_BANCO int NOT NULL PRIMARY KEY,
	VERSAO INT NOT NULL,
	BRANCH varchar(50) NOT NULL,
	NOME_ARQUIVO varchar(50) NOT NULL,
	DATA_ATUALIZACAO datetime NOT NULL,
)
